name: Update Project Dates

on:
  schedule:
    - cron: '0 12,18 * * *'

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Dates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PROJECT_NUMBER: 2
        run: |
          # Install dependencies
          sudo apt-get -y install jq

          # Debug repository info
          echo "Repository Owner: $REPO_OWNER"
          echo "Repository Name: $REPO_NAME"
          echo "Project Number: $PROJECT_NUMBER"

          # Get Project ID
          PROJECT_ID=$(gh api graphql -f query='
            query($owner: String!, $repo: String!, $projectNumber: Int!) {
              repository(owner: $owner, name: $repo) {
                projectV2(number: $projectNumber) {
                  id
                }
              }
            }' -f owner=$REPO_OWNER -f repo=$REPO_NAME -f projectNumber=$PROJECT_NUMBER | jq -r '.data.repository.projectV2.id')

          # Debug Project ID
          echo "Project ID: $PROJECT_ID"

          # Exit if Project ID is null
          if [ -z "$PROJECT_ID" ]; then
            echo "Error: Project ID is null. Check inputs and permissions."
            exit 1
          fi

          # Get Field IDs
          FIELDS_JSON=$(gh api graphql -f query='
            query($projectId: ID!) {
              node(id: $projectId) {
                ... on ProjectV2 {
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }' -f projectId=$PROJECT_ID | jq -r '.data.node.fields.nodes')

          STATUS_FIELD_ID=$(echo "$FIELDS_JSON" | jq -r '.[] | select(.name == "Status") | .id')
          START_DATE_FIELD_ID=$(echo "$FIELDS_JSON" | jq -r '.[] | select(.name == "Start Date") | .id')
          END_DATE_FIELD_ID=$(echo "$FIELDS_JSON" | jq -r '.[] | select(.name == "End Date") | .id')

          # Get all project items
          ITEMS_JSON=$(gh api graphql -f query='
            query($projectId: ID!) {
              node(id: $projectId) {
                ... on ProjectV2 {
                  items(first: 100) {
                    nodes {
                      id
                      fieldValues(first: 20) {
                        nodes {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field { id }
                          }
                          ... on ProjectV2ItemFieldDateValue {
                            date
                            field { id }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }' -f projectId=$PROJECT_ID | jq -r '.data.node.items.nodes')

          # Process items
          echo "$ITEMS_JSON" | jq -c '.[]' | while read -r ITEM; do
            ITEM_ID=$(echo "$ITEM" | jq -r '.id')
            STATUS=$(echo "$ITEM" | jq -r '.fieldValues.nodes[] | select(.field.id == "'$STATUS_FIELD_ID'") | .name')
            START_DATE=$(echo "$ITEM" | jq -r '.fieldValues.nodes[] | select(.field.id == "'$START_DATE_FIELD_ID'") | .date')
            END_DATE=$(echo "$ITEM" | jq -r '.fieldValues.nodes[] | select(.field.id == "'$END_DATE_FIELD_ID'") | .date')

            TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            if [ "$STATUS" = "Doing" ] && [ -z "$START_DATE" ]; then
              echo "Setting Start Date for $ITEM_ID"
              gh api graphql -f query='
                mutation ($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: $projectId,
                      itemId: $itemId,
                      fieldId: $fieldId,
                      value: { date: $date }
                    }
                  ) { clientMutationId }
                }' -f projectId=$PROJECT_ID -f itemId=$ITEM_ID -f fieldId=$START_DATE_FIELD_ID -f date=$TIMESTAMP
            fi

            if [ "$STATUS" = "Done" ] && [ -z "$END_DATE" ]; then
              echo "Setting End Date for $ITEM_ID"
              gh api graphql -f query='
                mutation ($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: $projectId,
                      itemId: $itemId,
                      fieldId: $fieldId,
                      value: { date: $date }
                    }
                  ) { clientMutationId }
                }' -f projectId=$PROJECT_ID -f itemId=$ITEM_ID -f fieldId=$END_DATE_FIELD_ID -f date=$TIMESTAMP
            fi
          done
